apiVersion: v2
name: uptime-com-exporter
description: Prometheus exporter for uptime.com monitoring checks
type: application
version: 0.1.0
appVersion: "0.0.0"
keywords:
  - prometheus
  - exporter
  - uptime
  - monitoring
home: https://github.com/gxben/uptime-com-exporter
sources:
  - https://github.com/gxben/uptime-com-exporter
maintainers:
  - name: Benjamin Zores
    email: bzores@cinemo.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
