{{- if not .Values.uptime.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-com-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-com-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ required "uptime.apiKey is required when not using uptime.existingSecret" .Values.uptime.apiKey | quote }}
{{- end }}
