name: Vulnerabilities Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  vuln:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install govulncheck
        run: GOBIN="$(pwd)/bin/" go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: bin/govulncheck ./...
